#!/bin/bash

echo
echo "---------------------------------------------------------"
echo "localhost@9201/_plugin/kopf (kopf plugin)"
echo "---------------------------------------------------------"
curl http://localhost:9201/_plugin/kopf

echo
echo "---------------------------------------------------------"
echo "localhost@9200 (elasticsearch)"
echo "---------------------------------------------------------"
curl http://localhost:9200

echo
echo "---------------------------------------------------------"
echo "nginx config"
echo "---------------------------------------------------------"
cat /etc/nginx/sites-available/default

echo
echo "---------------------------------------------------------"
echo "Netstat Status"
echo "---------------------------------------------------------"
/bin/netstat -tlpn

echo
echo "---------------------------------------------------------"
echo "Logstash Forwarder Error Log"
echo "---------------------------------------------------------"
tail /var/log/logstash-forwarder/logstash-forwarder.err
echo
echo "---------------------------------------------------------"
echo "Service Status"
echo "---------------------------------------------------------"
service logstash status
service logstash-forwarder status
service elasticsearch status
service kibana status
service nginx status

echo
echo "---------------------------------------------------------"
echo "Cluster Status"
echo "---------------------------------------------------------"
curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'

echo


